# Import Packages


In [702]:
import pandas as pd
from sklearn.linear_model import Perceptron
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
import numpy as np
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import numpy as np

# Loading Datasets

In [703]:
glass = pd.read_csv("glass data short.csv", header = None)
glass.head()

0      1     2     3      4     5      6     7     8  9
0  1.52777  12.64  0.00  0.67  72.02  0.06  14.40  0.00  0.00  2
1  1.51909  13.89  3.53  1.32  71.81  0.51   8.78  0.11  0.00  1
2  1.51837  13.14  2.84  1.28  72.85  0.55   9.07  0.00  0.00  1
3  1.52739  11.02  0.00  0.75  73.08  0.00  14.96  0.00  0.00  2
4  1.52020  13.98  1.35  1.63  71.76  0.39  10.56  0.00  0.18  2

# Data Cleaning

In [704]:
glass = glass.rename(columns = {0: 'A',1: 'B',2: 'C',3: 'D',4: 'E',5: 'F',6: 'G',7: 'H',8: 'I',9 : 'Label'})

y_train = glass['Label']
glass = glass.drop(columns = ['Label'])
x_train = glass

# Defining the Model

In [705]:
clf = MLPRegressor(
    hidden_layer_sizes=(2,),  activation='relu', solver='adam', alpha=0.001, batch_size='auto',
    learning_rate='constant', learning_rate_init=0.01, power_t=0.5, max_iter=1000, shuffle=True,
    random_state=9, tol=0.0001, verbose=False, warm_start=False, momentum=0.9, nesterovs_momentum=True,
    early_stopping=False, validation_fraction=0.1, beta_1=0.9, beta_2=0.999, epsilon=1e-08)

clf.fit(x_train, y_train)                          

MLPRegressor(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(2,), learning_rate='constant',
             learning_rate_init=0.01, max_iter=1000, momentum=0.9,
             n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
             random_state=9, shuffle=True, solver='adam', tol=0.0001,
             validation_fraction=0.1, verbose=False, warm_start=False)

#  R_squared based on model

In [706]:
clf.score(x_train,y_train)

0.8502728540558051

In [707]:
glass['predicted'] = clf.predict(x_train)

glass.head()

A      B     C     D      E     F      G     H     I  predicted
0  1.52777  12.64  0.00  0.67  72.02  0.06  14.40  0.00  0.00   1.470728
1  1.51909  13.89  3.53  1.32  71.81  0.51   8.78  0.11  0.00   1.525240
2  1.51837  13.14  2.84  1.28  72.85  0.55   9.07  0.00  0.00   1.630929
3  1.52739  11.02  0.00  0.75  73.08  0.00  14.96  0.00  0.00   1.470728
4  1.52020  13.98  1.35  1.63  71.76  0.39  10.56  0.00  0.18   2.510868

In [708]:
glass['predicted'] = glass['predicted'].astype(float)

# Binning


In [709]:
for index, row in glass.iterrows():
    if (glass.iloc[index]['predicted'] < 1.5):
        glass.iloc[index]['predicted'] = 1
        
    elif ((glass.iloc[index]['predicted'] >= 1.5) and (glass.iloc[index]['predicted'] <= 4.0)):
        glass.iloc[index]['predicted'] = 2
    
    elif (glass.iloc[index]['predicted'] > 4):
        glass.iloc[index]['predicted'] = 6

In [710]:
glass['Label'] = y_train

# SSR, SSE, R_squared


In [711]:
def ssr(y_true, y_pred):
    ssr = ((y_true - y_pred) ** 2).sum()
    return(ssr)

In [712]:
def ss(y_true, y_pred):
    ss = ((y_true - y_true.mean()) ** 2).sum()
    return(ss)

In [713]:
def r_squared(y_true, y_pred):
    ssr = ((y_true - y_pred) ** 2).sum()
    ss = ((y_true - y_true.mean()) ** 2).sum()
    r_squared = (1 - (ssr/ss))
    return(r_squared)

In [714]:
print('SSR =', ssr(y_train, glass["predicted"]))
print('ss=', ss(y_train, glass["predicted"]))
print('r_squared=',r_squared(y_train, glass["predicted"]))

SSR = 114.0
ss= 520.3045977011495
r_squared= 0.7808975732605791


# Number of records in each class and accuracy of class assignment

In [715]:
def ind_acc(a,dataframe):
    correctly_classified = 0
    total_occurances = 0
    
    for index, row in glass.iterrows():
        if ((dataframe.iloc[index]['predicted'] == a) and (dataframe.iloc[index]['Label'] == a)):
            correctly_classified += 1
                       
    total_occurances = (dataframe['Label'] == a).sum()
    
    accuracy = ((correctly_classified) /total_occurances) * 100
    print("correctly predicted count of",a, " =",  correctly_classified)
    print("total occurances of",a,"=", total_occurances)
    print("accuracy of predicting",a,"=", accuracy)
    return

In [733]:
accuracy_1 = ind_acc(1,glass)
print(accuracy_1)

correctly predicted count of 1  = 60
total occurances of 1 = 69
accuracy of predicting 1 = 86.95652173913044
None


In [732]:
accuracy_2 = ind_acc(2,glass)
print(accuracy_2)

correctly predicted count of 2  = 43
total occurances of 2 = 76
accuracy of predicting 2 = 56.57894736842105
None


In [731]:
accuracy_6 = ind_acc(6,glass)
print(accuracy_6)

correctly predicted count of 6  = 26
total occurances of 6 = 29
accuracy of predicting 6 = 89.65517241379311
None


# Overall accuracy

In [719]:
def overall_accuracy(dataframe):
    correctly_classified = 0
    
    for index, row in glass.iterrows():
        if (dataframe.iloc[index]['predicted'] == dataframe.iloc[index]['Label'] ):
            correctly_classified += 1
                       
    
    accuracy = ((correctly_classified) /(len(dataframe))) * 100
    print("Total count of correctly classified = ", correctly_classified)
    print("Total number of examples = ",len(dataframe))
    print("Overall accuracy of the model = ",accuracy)
    return 

In [730]:
print(overall_accuracy(glass))

Total count of correctly classified =  129
Total number of examples =  174
Overall accuracy of the model =  74.13793103448276
None


# Confusion Matrix

In [721]:
def classify(a,b,c,dataframe):
    correctly_classified = 0
    total_occurances = 0
    count_1 = 0
    count_2 = 0
    count_3 = 0
    
    for index, row in glass.iterrows():
        if ((dataframe.iloc[index]['Label'] == a)):
            total_occurances += 1
            
            if ((dataframe.iloc[index]['Label'] == a) and (dataframe.iloc[index]['predicted'] == a)):
                count_1 +=1
            
            
            if ((dataframe.iloc[index]['Label'] == a) and (dataframe.iloc[index]['predicted'] == b)):
                count_2 +=1
            
            
            if ((dataframe.iloc[index]['Label'] == a) and (dataframe.iloc[index]['predicted'] == c)):
                count_3 +=1
            
    print("in class ",a, "assigned class ",a,"=", count_1)
    print("in class ",a, "assigned class ",b,"=", count_2)
    print("in class ",a, "assigned class ",c,"=", count_3)
    print("total predicted",a, "=",total_occurances)
    return

In [729]:
print(classify(1,2,6,glass))

in class  1 assigned class  1 = 60
in class  1 assigned class  2 = 9
in class  1 assigned class  6 = 0
total predicted 1 = 69
None


In [728]:
print(classify(2,1,6,glass))

in class  2 assigned class  2 = 43
in class  2 assigned class  1 = 32
in class  2 assigned class  6 = 1
total predicted 2 = 76
None


In [727]:
print(classify(6,1,2,glass))

in class  6 assigned class  6 = 26
in class  6 assigned class  1 = 1
in class  6 assigned class  2 = 2
total predicted 6 = 29
None


In [725]:
def confusion(y_true,y_pred):
    matrix = np.transpose(confusion_matrix(y_train, glass['predicted'], labels=[1, 2, 6]))
    return(matrix)

In [726]:
print(confusion(y_train, glass["predicted"]))

[[60 32  1]
 [ 9 43  2]
 [ 0  1 26]]
